name = "SummationByPartsOperatorsExtra"
uuid = "213abaa5-c2d1-49c7-a86b-a2b7aa43ec15"
authors = ["Joshua Lampert <joshua.lampert@uni-hamburg.de> and contributors"]
version = "0.1.0-DEV"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[extensions]
SummationByPartsOperatorsExtraOptimForwardDiffExt = ["Optim", "ForwardDiff"]
SummationByPartsOperatorsExtraMeshesExt = "Meshes"

[compat]
ArgCheck = "1, 2"
AutoHashEquals = "0.2, 1, 2"
ForwardDiff = "0.10"
LinearAlgebra = "1"
Meshes = "0.53"
Optim = "1.12"
PreallocationTools = "0.4.26"
Reexport = "1.2"
SimpleUnPack = "1"
SparseArrays = "1"
SummationByPartsOperators = "0.5.78"
julia = "1.10"
