name = "SummationByPartsOperatorsExtra"
uuid = "213abaa5-c2d1-49c7-a86b-a2b7aa43ec15"
authors = ["Joshua Lampert <joshua.lampert@uni-hamburg.de> and contributors"]
version = "0.1.0-DEV"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolynomialBases = "c74db56a-226d-5e98-8bb0-a6049094aeea"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
MeshIntegrals = "dadec2fd-bbe0-4da4-9dbe-476c782c8e47"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[extensions]
SummationByPartsOperatorsExtraManifoldsManoptForwardDiffExt = ["Manifolds", "Manopt", "ForwardDiff", "RecursiveArrayTools"]
SummationByPartsOperatorsExtraMeshIntegralsExt = ["Meshes", "MeshIntegrals"]
SummationByPartsOperatorsExtraMeshesExt = "Meshes"
SummationByPartsOperatorsExtraMeshesMakieExt = ["Meshes", "Makie"]
SummationByPartsOperatorsExtraOptimForwardDiffExt = ["Optim", "ForwardDiff"]

[compat]
ArgCheck = "1, 2"
AutoHashEquals = "0.2, 1, 2"
DiffEqCallbacks = "4"
ForwardDiff = "0.10, 1"
LinearAlgebra = "1"
Makie = "0.23"
Manifolds = "0.10"
Manopt = "0.5"
MeshIntegrals = "0.16"
Meshes = "0.53"
Optim = "1.12"
PolynomialBases = "0.4.24"
PreallocationTools = "0.4.26"
RecursiveArrayTools = "3.33"
Reexport = "1.2"
SciMLBase = "2.78"
SimpleUnPack = "1"
SparseArrays = "1"
StaticArrays = "1.9"
StatsBase = "0.34"
SummationByPartsOperators = "0.5.81"
julia = "1.11"
