name = "SummationByPartsOperatorsExtra"
uuid = "213abaa5-c2d1-49c7-a86b-a2b7aa43ec15"
authors = ["Joshua Lampert <joshua.lampert@uni-hamburg.de> and contributors"]
version = "0.1.0-DEV"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"

[compat]
Reexport = "1.2"
SummationByPartsOperators = "0.5.78"
julia = "1.10"
